name: Application checks

on:
  pull_request:
    branches: [trunk]
  push:
    branches: ['feat/**', 'fix/**']

permissions:
  contents: read

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - run: npm ci
      - run: npm test
      - run: npm run build
